version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: secure_postgres_db
    environment:
      POSTGRES_USER: iquirium_admin
      POSTGRES_PASSWORD: S3cur3P@ssw0rd!
      POSTGRES_DB: iquirium_project_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
